### PR TITLE
Use elementClasses from base Component instead of cssClass

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
👍

**Comment by mthadley** [comment]
I believe you don't even need to add elementClasses as an explicit parameter to the template or component. It should always be merged with the classes of the container element. Good idea to double check though.

**Comment by jbalsas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
